# character = open("people1-exercise.txt","r")
# character.read("1:rishabh - meerut\n") 
# character.read("2:imtiyaz - delhi\n")
# character.read("3:nilima - cochin\n")
# character.read("4:rati - shimla\n")
# character.read("5:ayishah - delhi\n")
# character.read("6:raghu - shimla\n")
# character.read("7:naseer - kanpur\n")
# character.read("8:karthikeyan - delhi\n")
# character.read("9:salma - jaipur\n")
# character.read("10:pankaj - delhi\n")
# character.read("11:brijesh - delhi\n")
# character.read("12:govind - delhi\n")
# character.read("13:puneet - shimla\n")
# character.read("14:siddhi - delhi\n")
# character.read("15:suman - jaipur\n")
# character.read("16:rajeev - shimla\n")
# character.read("17:mohinder - delhi\n")
# character.read("18:rajendra - jaipur\n")
# character.read("19:priyanka - shimla\n")
# character.read("20:neela - delhi\n")
# character.read("21:sashi - jaipur\n")
# character.read("22:sarika - delhi\n")
# character.read("23:deepti - shimla\n")
# character.read("24:harshad - delhi\n")
# character.read("25:trishna - raipur\n")
# character.read("26;pradeep - jaipur\n")
# character.read("27:sekhar - delhi\n")
# character.read("28:nand - delhi\n")
# character.read("29:anoop - delhi\n")
# character.read("30:balwinder - tokyo")
# character.close()

x=open("test_file.txt","r")
y=x.readlines()
a = len(y)
print(a)



x=open("test_file.txt","r")
y=x.read()
print(y)



